development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: 
  password:

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: store_production
  pool:     5
  username:
  password:
